### ISSUE TITLE
Configurable idle timeouts?

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-nginx#66]
It may be helpful to be able to configure `proxy_read_timeout` via ENV, for example.

**Comment by krallin** [comment]
@fancyremarker 
Done as of https://github.com/aptible/docker-nginx/pull/85; if we want to support this for ALBs, all that's left to do is let the VHOST define a custom idle timeout and appropriate timeouts will scale properly (idle timeout on the ALB, as well as keep alive and idle timeouts here in Nginx).

For ELBs, we'd still have a little bit of work to support this, since we don't currently configure timeouts on the ELB (at least not that I know of).

**Comment by krallin** [comment]
FWIW, this is supported as a of a couple months ago via the `IDLE_TIMEOUT` variable: https://www.aptible.com/support/topics/enclave/endpoint-timeouts/
